# Inherit common board flags
-include device/lenovo/msm8916-common/BoardConfigCommon.mk

# Asserts
TARGET_OTA_ASSERT_DEVICE := p1a42,passion_row

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/lenovo/p1a42/bluetooth

# Kernel
TARGET_KERNEL_CONFIG := passion_row-user_defconfig
FORCE_32_BIT := true

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 41940355
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2684354560
BOARD_USERDATAIMAGE_PARTITION_SIZE := 26843545600

# Recovery
TARGET_RECOVERY_FSTAB := device/lenovo/p1a42//rootdir/fstab.qcom
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_SUPPRESS_EMMC_WIPE := true
